version: "3.1"
services:
  bycar_api:
    image: "node:16"
    container_name: ${SERVICE_NAME}
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    networks:
      - internal
      - proxy
    command: "yarn start"
    restart: "always"
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      - traefik.http.routers.${SERVICE_NAME}-web.middlewares=redirect-to-https
      - traefik.http.routers.${SERVICE_NAME}-web.rule=Host(`${SERVICE_DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}-web.entrypoints=web
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_DOMAIN}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencrypt-resolver
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=4000

networks:
  internal:
    external: false
  proxy:
    external: true
