services:
  bycar-website:
    container_name: bycar-website
    build:
      context: .
    environment:
      - API_URL=${API_URL}
      - CDN_URL=${CDN_URL}
      - NODE_ENV=${NODE_ENV}
    networks:
      - proxy

networks:
  proxy:
    external: true
